auto-save-interval: 120 # In seconds

sidebar:
  enabled: false
  title: '(SERVER NAME)'
  lines:
    - ''
    - 'Clan: %clan_name%'
    - ''
    - 'Clan Leader: %clan_leader%'
    - ''
    - 'Clan Members: %clan_member_count%'
    - ''
    - 'YOUR SERVER IP'
