name: '${artifactId}'
version: '${version}'
main: dev.idqnutlikeit.clans.ClanPlugin
api-version: '1.20'
authors: [ IDqnutLikeIt, Azoraqua ]
softdepend: [ PlaceholderAPI, Vault ]

libraries:
  - 'me.mattstudios.utils:matt-framework:1.4'
  - 'net.kyori:adventure-api:4.14.0'
  - 'net.kyori:adventure-platform-bukkit:4.3.0'
  - 'com.google.guava:guava:32.1.2-jre'
  - 'org.projectlombok:lombok:1.18.28'
  - 'org.apache.commons:commons-collections4:4.4'

permissions:
  ${base.name}.*:
    description: Permission to all features of the DqnutClans plugin.
    default: op
    children:
      - '${base.name}.admin'
      - '${base.name}.user'
  ${base.name}.admin:
    description: Permission to administrative features of the DqnutClans plugin.
    default: op
    children:
      - '${base.name}.user'
  ${base.name}.user:
    description: Permission to regular features of the ${base.name} plugin.
    default: true
    children:
      - '${base.name}.create'
      - '${base.name}.disband'
      - '${base.name}.list'
      - '${base.name}.info'
      - '${base.name}.info.others'
      - '${base.name}.kick'
      - '${base.name}.ban'
      - '${base.name}.unban'
      - '${base.name}.mute'
      - '${base.name}.unmute'
      - '${base.name}.invite'
      - '${base.name}.leave'
      - '${base.name}.accept'
      - '${base.name}.deny'
      - '${base.name}.setspawn'
      - '${base.name}.spawn'
      - '${base.name}.chat'
      - '${base.name}.applications'
