name: '${artifactId}'
version: '${version}'
main: dev.idqnutlikeit.clans.ClanPlugin
api-version: '1.20'
authors: [ IDqnutLikeIt, Azoraqua ]
softdepend: [ PlaceholderAPI, Vault ]

libraries:
  - 'me.mattstudios.utils:matt-framework:1.4'
  - 'net.kyori:adventure-api:4.14.0'
  - 'net.kyori:adventure-platform-bukkit:4.3.0'
  - 'com.google.guava:guava:32.1.2-jre'
  - 'org.projectlombok:lombok:1.18.28'
  - 'org.apache.commons:commons-collections4:4.4'

commands:
  clans:
    description: Core command of DqnutClans.
    aliases: [ clan, c ]
    usage: /<command>

permissions:
  clans.*:
    description: Permission to all features of the DqnutClans plugin.
    default: op
    children:
      - 'clans.admin'
      - 'clans.member'
  clans.admin:
    description: Permission to administrative features of the DqnutClans plugin.
    default: op
    children:
      - 'dqnutclans.create'
      - 'dqnutclans.disband'
      - 'dqnutclans.list'
      - 'dqnutclans.info'
      - 'dqnutclans.info.others'
      - 'dqnutclans.kick'
      - 'dqnutclans.ban'
      - 'dqnutclans.invite'
      - 'dqnutclans.join'
      - 'dqnutclans.leave'
      - 'dqnutclans.accept'
      - 'dqnutclans.deny'
      - 'dqnutclans.invites'
      - 'dqnutclans.invites.others'
      - 'dqnutclans.chat'
  clans.member:
    description: Permission to regular features of the DqnutClans plugin.
    default: true
    children:
      - 'dqnutclans.create'
      - 'dqnutclans.disband'
      - 'dqnutclans.list'
      - 'dqnutclans.info'
      - 'dqnutclans.kick'
      - 'dqnutclans.ban'
      - 'dqnutclans.invite'
      - 'dqnutclans.join'
      - 'dqnutclans.leave'
      - 'dqnutclans.accept'
      - 'dqnutclans.deny'
      - 'dqnutclans.invites'
      - 'dqnutclans.chat'
