name: '${artifactId}'
version: '${version}'
main: dev.idqnutlikeit.clans.ClanPlugin
api-version: '1.20'

libraries:
  - 'me.mattstudios.utils:matt-framework:1.4'
  - 'net.kyori:adventure-api:1.14.0'
  - 'net.kyori:adventure-platform-bukkit:4.3.0'
  - 'io.papermc:paperlib:1.0.7'
  - 'com.google.guava:guava:32.1.2-jre'

commands:
  clans:
    description: Core command of DqnutClans.
    aliases: [ clan, c ]
    usage: /<command>

permissions:
  clans.*:
    description: Permission to all features of the DqnutClans plugin.
    default: op
    children:
      - 'clans.admin'
      - 'clans.member'
  clans.admin:
    description: Permission to administrative features of the DqnutClans plugin.
    default: op
    children:
      - 'dqnutclans.help'
      - 'dqnutclans.create'
      - 'dqnutclans.disband'
      - 'dqnutclans.disband.others'
      - 'dqnutclans.list'
      - 'dqnutclans.info'
      - 'dqnutclans.kick'
      - 'dqnutclans.ban'
      - 'dqnutclans.invite'
      - 'dqnutclans.join'
      - 'dqnutclans.leave'
      - 'dqnutclans.accept'
      - 'dqnutclans.deny'
      - 'dqnutclans.chat'
  clans.member:
    description: Permission to regular features of the DqnutClans plugin.
    default: true
    children:
      - 'dqnutclans.help'
      - 'dqnutclans.create'
      - 'dqnutclans.disband'
      - 'dqnutclans.list'
      - 'dqnutclans.info'
      - 'dqnutclans.kick'
      - 'dqnutclans.ban'
      - 'dqnutclans.invite'
      - 'dqnutclans.join'
      - 'dqnutclans.leave'
      - 'dqnutclans.accept'
      - 'dqnutclans.deny'
      - 'dqnutclans.chat'